spring:
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      host: localhost
      port: 6379

payroll:
  events:
    ttl-days: 30

server:
  port: 8080

logging:
  level:
    root: INFO
    br.com.example.payroll: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{correlationId}] %logger{36} - %msg%n"
